### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by fratcliffe** [logzio/telegraf-docker-collector-metrics#3]
`EXCLUED_IMAGES` [here](https://github.com/logzio/telegraf-docker-collector-metrics/blob/master/README.md?plain=1#L33) should be `EXCLUDED_IMAGES`

This typo is also present in the instructions for setting up the metrics collector in the logz.io app itself.

**Comment by mirii1994** [comment]
Hi @fratcliffe thanks for notifying us about this!
We the instructions in the repo and in the in-app documentation were fixed :)
